feat: added UI for homepage
muskanbagrecha/social-media-react-app pull request #1
Opened 2022-05-11 19:49 UTC by muskanbagrecha

2022-05-13 04:50 UTC, zoef-yt requested changes

2022-05-13 04:50 UTC, zoef-yt commented on src/pages/homepage/components/who-to-follow/WhoToFollow.tsx
> +          {data.map((user) => (
Destructure user

2022-05-13 04:50 UTC, zoef-yt commented on src/pages/homepage/components/post/Post.css
> +    /* padding: 0 8px; */
remove the comments

2022-05-13 04:50 UTC, zoef-yt commented on src/pages/homepage/components/feed-navigation/FeedNavigation.tsx
> +          </li> */}
remove commented code.

2022-05-13 04:50 UTC, zoef-yt commented on src/pages/homepage/components/feed-navigation/FeedNavigation.tsx
> +          </li>
You can convert these into one component as you are here.

2022-05-13 04:50 UTC, zoef-yt commented on src/context/theme-context/ThemeContext.tsx
> +import { createContext, useContext, useEffect, useState } from "react";
Question: I can see you have theme context but the switch of the theme is not happening bug or not wired yet?

2022-05-13 04:50 UTC, zoef-yt commented on src/index.css
> +    background-color: #D2CBE7;
You var for colour.

2022-05-13 04:50 UTC, zoef-yt commented on src/index.tsx
> +    </BrowserRouter>
Appreciation: Nice abstraction.

2022-05-13 04:50 UTC, zoef-yt commented on src/pages/homepage/components/create-post/CreatePost.tsx
> +          </span>
These extra span can be removed.

2022-05-13 04:50 UTC, zoef-yt commented on src/pages/homepage/components/feed-navigation/FeedNavigation.css
> +    z-index: 2;
Would prefer if you use var for z-index just an opinion.

2022-05-13 04:50 UTC, zoef-yt commented on src/pages/homepage/components/main-feed/MainFeed.css
> +    "posts"; */
remove commented code.

2022-05-13 04:50 UTC, zoef-yt commented on src/pages/homepage/components/post/Post.tsx
> +        <div>
This extra div can be removed.

2022-05-13 04:50 UTC, zoef-yt commented on src/pages/homepage/components/post/Post.tsx
> +        <div className="flex justify-between"></div>
This extra div can be removed.

2022-05-16 17:05 UTC, rahulyadav139 approved these changes

2022-05-16 17:05 UTC, rahulyadav139 commented on src/pages/homepage/components/moments/Moments.css
> +        clip-path: circle();
Appreciation: great you have used the circle method.

2022-05-16 17:05 UTC, rahulyadav139 commented on src/pages/homepage/components/post/Post.tsx
> +        alt=""
alt tag is empty. Please give some value to this tag.

2022-05-20 18:13 UTC, muskanbagrecha commented
All comments will be addressed in subsequent PRs.

2022-05-20 18:13 UTC, merged